### ISSUE TITLE
Locked into Trackview after maneuvering a satellite

### ISSUE THREAD

**Issue by onufert** [RemoteTechnologiesGroup/RemoteTech#580] opened 2016-04-24 13:14 UTC
When returning back to the SpaceCenter after maneuvering a satellite probe, whenever I enter the Trackstation view it becomes a one way trip. None of my objects are shown in the track view and the "Leave Facility" button doesn't work. Skimming through the log only exceptions I see are the ones below.

```
[WRN 08:59:27.709] [HighLogic]: =========================== Scene Change : From SPACECENTER to TRACKSTATION =====================
[LOG 08:59:27.719] ScaleModList: listSize 123 maxListSize 1233
[EXC 08:59:27.880] NullReferenceException: Object reference not set to an instance of an object
	RemoteTech.UI.FocusOverlay.OnVDestroy (.Vessel v)
	EventData`1[Vessel].Fire (.Vessel data)
	Vessel.OnDestroy ()
[EXC 08:59:27.882] NullReferenceException: Object reference not set to an instance of an object
	RemoteTech.UI.FocusOverlay.OnVDestroy (.Vessel v)
	EventData`1[Vessel].Fire (.Vessel data)
	Vessel.OnDestroy ()
[EXC 08:59:27.883] NullReferenceException: Object reference not set to an instance of an object
	RemoteTech.UI.FocusOverlay.OnVDestroy (.Vessel v)
	EventData`1[Vessel].Fire (.Vessel data)
	Vessel.OnDestroy ()
```
Log shows AddonLoader loading other stuff, then this (which I'm guessing is when the trackview locks up?)

```
[EXC 08:59:28.147] NullReferenceException
	FloatingOrigin.setOffset (Vector3d refPos)
	FloatingOrigin.SetOffset (Vector3d refPos)
	PSystemSetup.SetTrackingStation ()
	PSystemSetup.OnLevelWasLoaded (Int32 level)
[EXC 08:59:28.527] NullReferenceException: Object reference not set to an instance of an object
	KSP.UI.Screens.SpaceTracking.buildVesselsList ()
	KSP.UI.Screens.SpaceTracking.Start ()
```

**Comment by d4rksh4de** [comment] 2016-04-24 13:59
Seems duplicate of #568, which is already fixed. @onufert, please try latest Pre-release build.

**Comment by tomekpiotrowski** [comment] 2016-04-26 19:08
Please re-open if this still occurs with the latest build.

**Closed by tomekpiotrowski** 2016-04-26 19:08 UTC
Labels: Duplicate
