### ISSUE TITLE
Update RemoteTech.version to 1.1.3

### ISSUE THREAD

**Issue by MrCamoga** [RemoteTechnologiesGroup/RemoteTech#655] opened 2016-06-25 16:36 UTC

**Comment by Demeterp** [comment] 2016-06-26 19:25
MissingMethodException: Method not found: 'TimeWarp.SetRate'.
  at RemoteTech.FlightComputer.FlightComputer.OnUpdate () [0x00000] in <filename unknown>:0 
  at RemoteTech.Modules.ModuleSPU.Update () [0x00000] in <filename unknown>:0

**Comment by tomekpiotrowski** [comment] 2016-06-26 19:26
Duplicate of #645

**Closed by tomekpiotrowski** 2016-06-26 19:26 UTC
