### ISSUE TITLE
Antennas auto extend and can't retract

### ISSUE THREAD

**Issue by AndresHdzArv** [RemoteTechnologiesGroup/RemoteTech#798] opened 2019-11-12 14:49 UTC
In editor antennas deploy themselves and can't retract them. They don't respond 
KSP. 1.8.1

**Comment by KSP-TaxiService** [comment] 2019-11-13 12:57
Hi, 
Kindly assist to provide output_log.txt, screenshots of the self-deploy antennas and mod list, per [guidelines](https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/develop/CONTRIBUTING.md#bug-reports).

I do not replicate this issue on clean KSP 1.8.1 install with RT develop build.

Thanks.

**Comment by AndresHdzArv** [comment] 2019-11-13 13:36
[Selfdeployvideo.zip](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/3841376/Selfdeployvideo.zip)

**Comment by AndresHdzArv** [comment] 2019-11-13 13:36
That is the video with the issue

**Comment by AndresHdzArv** [comment] 2019-11-13 13:52
[KSP.log](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/3841441/KSP.log)

**Comment by KSP-TaxiService** [comment] 2019-11-14 13:49
Hi,
The video zip you attached is empty. Please re-upload the video.

Is the issue happening on Communotron 16 and Communotron 88-88 only, or all the deployable antennas? I ask this question because there are few animation errors for both antennas according to your log.
```
[LOG 07:49:01.973] ModuleAnimateGeneric: Could not find animation component 'antenna' - on part longAntenna failed to load! Check the model file
```
I usually see such errors related to the model changes by Restock mod.

**Comment by AndresHdzArv** [comment] 2019-11-14 13:59
[Selfdeployvideo.zip](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/3846800/Selfdeployvideo.zip)

**Comment by AndresHdzArv** [comment] 2019-11-14 14:00
The problem is with all antennas

**Comment by BTAxis** [comment] 2019-11-14 21:41
Not really. As far as I can see, this issue applies to the Communotron 16, 88-88 and HG-55 only. All other antennas, be they stock or modded, seem to be unaffected.

**Comment by AndresHdzArv** [comment] 2019-11-15 04:26
Those were the antennas I tested on it, so you may be right, even then, it’s still an important issue as they are the only antennas I have and if I can’t send them then I can’t advance my game

**Comment by KSP-TaxiService** [comment] 2019-11-15 14:46
Hi AndresHdzArv,

Can you move ReStock mod out of your game installation and check if the issue persists? The errors I found are related to this mod.

**Comment by BTAxis** [comment] 2019-11-15 14:52
I can confirm that removing ReStock does make this issue go away.

**Comment by AndresHdzArv** [comment] 2019-11-15 19:41
Yes, without ReStock everything works properly, will this be fixed?

**Comment by ChrisAdderley** [comment] 2019-11-17 02:38
I suspect this is an ordering issue. Order is currently
1. RemoteTech patches antenna to transform ModuleDeployableAntenna into ModuleAnimateGeneric
2. Restock changes the model
3. Restock tries to patch antenna's ModuleDeployableAntenna's animation name and fails
4. The RemoteTech-modfied ModuleAnimateGeneric is unhappy because the animation name does not exist.

Restock can ship a patch in the next version to target ModuleAnimateGeneric in the case that RemoteTech is installed.

**Comment by ChrisAdderley** [comment] 2019-11-17 02:53
I've uploaded a potential fix for this [here](https://github.com/PorktoberRevolution/ReStocked/blob/master/Distribution/Restock/GameData/ReStock/Compatibility/RemoteTech.cfg). It should resolve the issue.

**Comment by KSP-TaxiService** [comment] 2019-11-17 07:58
Hi @ChrisAdderley,

Thanks so much for your assistance. 

I confirm the following antennas having the animation problem.
- HG-5 (Not Comm DTS-M1)
- Comm 16
- Comm HG-55
- Comm 88-88

I revise and incorporate your fix into the existing RemoteTech [patch](https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/develop/GameData/RemoteTech/RemoteTech_Restock_Antennas.cfg) for ReStock.

Kindly assist to decommission your fix on ReStock's side.

**Closed** 2019-11-17 08:00 UTC
Labels: Config, Other Mod, Verified Bug

**Comment by ChrisAdderley** [comment] 2019-11-18 08:13
Done.
