### ISSUE TITLE
The Flight Computer isn't working for KSP 1.7.2.2556

### ISSUE THREAD

**Issue by amlaurent** [RemoteTechnologiesGroup/RemoteTech#795] opened 2019-07-03 15:05 UTC
### Computer Configuration
**OS:** Mac OS X 10.14.5
**CPU:** Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4)
**RAM:** 16384
**GPU:** Intel(R) Iris(TM) Graphics 540 (1536MB)
**SM:** 46 (OpenGL 4.1 INTEL-12.9.22)
**RT Formats:** ARGB32, Depth, ARGBHalf, Shadowmap, RGB565, ARGB4444, ARGB1555, Default, ARGB2101010, DefaultHDR, ARGB64, ARGBFloat, RGFloat, RGHalf, RFloat, RHalf, R8, ARGBInt, RGInt, RInt, RGB111110Float, RG32, RGBAUShort, RG16

### Installed Mods

B9PartSwitch
Chatterer
CommunityResourcePack
CommunityTechTree
ContractConfigurator
ContractPacks
CryoEngines
CryoTanks
DMagicOrbitalScience
DecayingRTGs
DeployableEngines
DynamicBatteryStorage
HideEmptyTechTreeNodes
KerbalEngineer
MechJeb2
NearFutureAeronautics
NearFutureConstruction
NearFutureElectrical
NearFutureLaunchVehicles
NearFutureProps
NearFuturePropulsion
NearFutureSolar
NearFutureSpacecraft
OrbitalLFOEngines
RemoteTech
SCANsat
StationPartsExpansionRedux
TriggerTech
UniversalStorage2
WildBlueIndustries
XenonHallThrusters
scatterer
ModuleManager.4.0.2.dll

**Issue Description**

In my save, RemoteTech's timed execution has worked perfectly until very recently, a time since which it has started acting frightfully out of sorts. The bugs manifest in two ways for manoeuvres I have teed up days or months or years in advance;

First, is that it first goes into the node position and then when it comes to the burn, it stops holding the NODE attitude. Re-engaging NODE ends the burn.

Second, it retains the NODE attitude but it miscalculates/misexecutes the burn, so it burns at T-0 instead of T-1/2 of Burn Time

I have a video documenting the NODE mode automatically shuts off as soon as the burn starts. Furthermore, node execution ends if I send a command to turn the NODE mode on. I ended the video shortly after this. However, if I left it as such, it would drift and continue burning, resulting in erroneous orbits.

Can you please help me?

https://youtu.be/-ZTwYk1PgBA

**Comment by KSP-TaxiService** [comment] 2019-07-04 14:37
Hi,

The node and maneuver execution commands are separate. Upon starting, the maneuver execution will de-activate the node command and activate its internal node command. This execution command will keep the vessel onto the node mark.

But what version is your RemoteTech? I thought the improper burning issue was fixed in version 1.9.1.

**Comment by amlaurent** [comment] 2019-07-04 15:34
Hey there,

Thanks for the reply! I did not know that the commands were separate. My
version is 1.9.2, paradoxically, this is the first time I have face the
improper burn issue on my side.

Would you like any more data from me? Would you like me to take a longer
video demonstrating this? Because Remotetech is definitely acting strange
in my saves.

Best,
Anna

**Comment by amlaurent** [comment] 2019-07-06 03:32
I have found additional bugs - such as a craft that should have a significant signal delay acting as if it's under local control. Would you like additional videos and logs? It's almost as if RT is broken for my save.

**Comment by KSP-TaxiService** [comment] 2019-07-12 15:04
Hi @amlaurent, sorry for delay.

Are you using CKAN to manage KSP mods? If yes, please export your mod list to share with me. This way, I can mass-install your mods on clean installation at my end.

It seems most of the issues encountered by you may be related to the incompatibilities or mod conflict or simply unsupported by RT. For example, 3rd-party probe cores of vessels with significant signal delay having "local-control" reaction could be not supported by RT.

**Comment by KSP-TaxiService** [comment] 2019-08-14 14:19
No further clarification is received on this issue.

**Comment by amlaurent** [comment] 2019-08-14 14:56
hey would it be possible to reopen the issue? I missed the email

**Comment by KSP-TaxiService** [comment] 2019-08-14 14:58
Sure, this issue is reopened now,

**Comment by KSP-TaxiService** [comment] 2019-08-19 12:58
@amlaurent, a gentle reminder on this clarification request.

**Comment by amlaurent** [comment] 2019-08-20 06:19
Ooof I keep forgetting, I'm so sorry. I don't use CKAN, but here's the mod
list;

B9PartSwitch
Chatterer
CommunityResourcePack
CommunityTechTree
ContractConfigurator
ContractPacks
CryoEngines
CryoTanks
DMagicOrbitalScience
DecayingRTGs
DeployableEngines
DynamicBatteryStorage
HideEmptyTechTreeNodes
KerbalEngineer
MechJeb2
NearFutureAeronautics
NearFutureConstruction
NearFutureElectrical
NearFutureLaunchVehicles
NearFutureProps
NearFuturePropulsion
NearFutureSolar
NearFutureSpacecraft
OrbitalLFOEngines
RemoteTech
SCANsat
StationPartsExpansionRedux
TriggerTech
UniversalStorage2
WildBlueIndustries
XenonHallThrusters
scatterer
ModuleManager.4.0.2.dll


ᐧ

**Comment by KSP-TaxiService** [comment] 2019-08-21 13:36
Hi,

I am unable to replicate the issue of half-burn timing on KSP 1.7.3 with RT 1.9.3 and most of your mods.
I am able to hit the half-time burn mark on all my attempts of stock engine, 3rd-party ion engine and LH2+Ox engine, like this example below.
![1](https://user-images.githubusercontent.com/22871614/63436541-71b0f000-c45b-11e9-8c27-e0eaf0228c39.PNG)

Are you still experiencing this issue on your side?

**Comment by amlaurent** [comment] 2019-08-22 00:31
Yeah! I'm on a mac, maybe that makes a difference?

**Comment by KSP-TaxiService** [comment] 2019-08-23 15:23
Hi, I doubt the difference between OSX and Windows makes a difference.

Anyway, I accidentally managed to replicate the issue by forgetting to activate the engine before clicking the maneuver burn command. This is incorrect usage because upon queuing this command, Flight Computer reads the current vessel state, included the engine state, to compute the timing.

With the engine shut down, Flight Computer computes 0 thrust and pins the burning start time at node time=0.

Please confirm if this is how you encounter the issue.

**Comment by amlaurent** [comment] 2019-08-24 03:13
Nope! It's not, perhaps I can try to update and try again? What can I do to
make this issue repeatable and predictable?

**Comment by KSP-TaxiService** [comment] 2019-08-24 14:44
Here're the steps to replicate the issue:

1. On your vessel in flight, shut down all engines.
![1](https://user-images.githubusercontent.com/22871614/63638861-f56b1680-c6bf-11e9-9c26-76ecd2f78608.PNG)
2. In Flight Computer, click EXEC command to queue the maneuver node burning
![2](https://user-images.githubusercontent.com/22871614/63638867-087de680-c6c0-11e9-95da-91fb3dd06dd3.PNG)
This command will compute 0 engine thrust and set the burning start time at node time=0 like this.
![3](https://user-images.githubusercontent.com/22871614/63638874-21869780-c6c0-11e9-9cd8-3a0473c027f4.PNG)

If this command is issued with activated engines, the burning start time should be half-way node time, as shown below.
![4](https://user-images.githubusercontent.com/22871614/63638880-3c590c00-c6c0-11e9-9fdc-73f934597999.PNG)

It is possible that the third-party engines you use are not supported by RemoteTech, which may read them as 0 thrust even if they are activated. The workaround to this is to use the different command, BURN to explicitly burn at target throttle for target duration at target starting time. instead of Flight Computer's auto-computation of maneuver node burning.
![5](https://user-images.githubusercontent.com/22871614/63638919-9f4aa300-c6c0-11e9-9261-e239fcf92385.PNG)

**Comment by KSP-TaxiService** [comment] 2019-08-30 13:26
Hi @amlaurent, are you able to replicate the issue on your side?

**Comment by amlaurent** [comment] 2019-08-30 17:30
Can you give me a few more days, please? I'm busy at work :(
ᐧ

**Comment by amlaurent** [comment] 2019-09-06 06:36
Hey TaxiService,

Thanks for being so patient with me. Apologies for all the delays, stuff
has been really busy. But I have managed to shoot a few videos (they aren't
edited or shortened to give you a sense of what's going on) in an updated
KSP 1.7.3.something something (I can't go back to the exact number that I
started with) and went through a few different scenarios;

First, was that I created an all-stock craft and executed burns on it. I
tried to see if it drifted. It didn't.

Second, was that I opened up another ion drive based craft with modded
parts (Neartea's parts) and see what happens. The drift occurred here.

Thirdly, I did another part stock, part Neartea-craft that then displayed
this "vibratory" behavior on KILL rotation that it doesn't display on stock
SAS. I also did a burn with it and noticed some drift.

I've put them all into 4 videos in this playlist for you to browse through;
https://www.youtube.com/watch?v=PZ6jOhFfAnY&list=PL4SWjGpuTpMMrLIiHF58KuFyF_8M3IyaU

If this is too tiresome, then I'm happy to give you the save and my mods as
is and let you play with it :)

Best,
Anna
ᐧ

**Comment by KSP-TaxiService** [comment] 2019-09-15 14:22
Hi,

At the beginning of the second video, you issued the delayed command of engine activation before issuing node execution. This is not right way because I mentioned in the previous message that upon issuing of the node execution command, Flight Computer read all current states of engines to compute the timing. By the time of your node execution command, the engine was not activated yet with that engine activation command still ticking.

Can you try again with the engine activated before issuing the node execution command? The reason  for this way of node execution command is Flight Computer has to act on all current (not future) vessel information when queuing such command.

For the third and last videos, the vibration is caused by Flight Computer aggressively orienting towards the maneuver point with narrow buffers (you can see very rapid oscillations in yaw and pitch). It is typically caused by weak structural joints (wobbling) or CoM not neatly in line with CoL in X or/and Y. It is not related to the incorrect burn start timing.

**Closed** 2019-10-19 06:26 UTC
