### ISSUE TITLE
preflight planing (suggestion?)

### ISSUE THREAD

**Issue by personal-assembly-reqired** [RemoteTechnologiesGroup/RemoteTech#434] opened 2015-05-27 09:20 UTC
It could be interesting to see the ability to "aim" directional antennas inside the VAB at satellites you already have in orbit (similar to how you can select them from the map view for instance) 

I sadly don’t have the experience with unity to even consider attempting something liek this but it is food for thought for any one on your "team" looking for an idea

**Comment by Peppie23** [comment] 2015-05-27 17:11
Hi @personal-assembly-reqired 
thanks for your post but i'll mark this as a duplicate of #257 (Pre-target antennae in VAB/SPH)

**Closed by Peppie23** 2015-05-27 17:11 UTC
