### ISSUE TITLE
Cannot use brakes

### ISSUE THREAD

**Issue by mferrie** [RemoteTechnologiesGroup/RemoteTech#659] opened 2016-06-28 22:18 UTC
1. Make a rover
2. Try to use the brakes.
The brakes and all the other action groups next to the altimeter are greyed out, and will not respond to either clicking or the hotkeys.

**Comment by tomekpiotrowski** [comment] 2016-06-28 22:19
Duplicate of #605

**Closed by tomekpiotrowski** 2016-06-28 22:19 UTC
Labels: Duplicate
