### ISSUE TITLE
Flight computer causes ship to aimlessly change attitudes with no apparent rhyme or reason

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#25] opened 2014-05-26 04:31 UTC
Original issue at Cilph/RemoteTech2#205.

tntristan12 wrote:

>  I am trying to get the computer to orient my ship surface prograde (though this seems to happen regardless of what commands I'm trying to give it), and the ship completely loses control and starts spinning in random directions (note, I'm saying "spinning" not "wobbling", as the ship is holding completely rigid), and never actually settles on the heading I'm trying to give it.
> 
> Actually, in that case it seemed to cause the issue when MechJeb was in control, but I have a craft that is demonstrating this same behavior regardless of whether or not I'm controlling from the MechJeb case or not.

SodaPopinski wrote:

> In order to make this bug happen, you need to change the "Control from Here" from the probe core to something else. That usually does it. You may need to set it back to the original probe core. I haven't tested it with 2 probe cores, but it happens when I control from a docking port, and switch back. I removed all other mods, and this still happens.

**Comment by KSP-TaxiService** [comment] 2018-08-13 14:07
Closing with lacking of insight on this particular behaviour and reproduction difficulty since lot of changes made to Flight Computer.

**Closed by KSP-TaxiService** 2018-08-13 14:07 UTC
Labels: FlightComputer, From Cilph/RemoteTech2, Old Issue: Reconfirm
