### ISSUE TITLE
Order's queue lost when switching vessels (or going SC)

### ISSUE THREAD

**Issue by Jacchus** [RemoteTechnologiesGroup/RemoteTech#820] opened 2020-11-13 17:19 UTC
OS: Windows 10
KSP: 1.10 (with both DLC)
Problem: When switching vessels or returning to space center the order queue is lost. Nodes and everything are ok, but order queue is empty.

Reproduction steps:
Simply switching vessels and returning 
        
Logs:
    I'm adding a log extract where I created a exec order from a node, switched to SC, and returned. 2 Times (one return with KAC jump to vessel option, and other one with tracking station "fly" option. 
The vessel is "Mun Relee 2"
[RTLOG.txt.txt](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/5538270/RTLOG.txt.txt)

List of mods (CKAN):
[ListOfMods.txt](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/5538276/ListOfMods.txt)

**Comment by KSP-TaxiService** [comment] 2020-11-17 15:29
Hi, 

Thanks for the log and mod list. It helps greatly in identifying `Bon Voyage` mod as the root cause of command queue lost when switching vessels.

I am debugging why this is the case.

**Comment by Jacchus** [comment] 2020-11-17 15:36
Thanks a lot for your work. If you need any more info or anything please contact me, I haven't played the game while waiting for your feedback

**Comment by KSP-TaxiService** [comment] 2020-11-19 15:21
Hi, I re-applied the fix for the issue that I thought was "resolved" in an unrelated fix.

Kindly assist to try out the [latest develop build](https://github.com/RemoteTechnologiesGroup/RemoteTech/releases/tag/RemoteTech-1.9.8-28-develop) and verify that command queue is saved and loaded successfully.

**Comment by Jacchus** [comment] 2020-11-20 18:11
Looks **FIXED**, I'll keep checking but with vessel switch and loading game it works. Thanks a lot!
Nice touch autodeleting KAC alarms

**Comment by KSP-TaxiService** [comment] 2020-11-21 07:35
Thanks, I will set this issue to resolved and the fix will be in a next RemoteTech release.

**Closed by KSP-TaxiService** 2020-11-21 07:35 UTC
Labels: Other Mod, Verified Bug
