### ISSUE TITLE
No dishes in VAB

### ISSUE THREAD

**Issue by LordFlameStryke** [RemoteTechnologiesGroup/RemoteTech#621] opened 2016-05-07 02:02 UTC
[Dragon Fyre.zip](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/253231/Dragon.Fyre.zip)

I had RemoteTech 1.7.0 working properly at one point, then I changed some of my mods, none of which should have affected RemoteTech.  Now, when I go into my VAB, I have no dishes only the basic antennae.  However putting an omni antenna on my ship doesn't get me a signal on my probe core either.

After reinstalling RemoteTech, I have the dishes in my tech tree as usual, but they're not in the parts list for the VAB.  Zip file contains my persistent save plus my RemoteTech config file for that save.

![tech tree](https://cloud.githubusercontent.com/assets/19233096/15089638/b7bab20c-13c4-11e6-90c6-e90c79ac4541.jpg)
![vab](https://cloud.githubusercontent.com/assets/19233096/15089639/b7bce8f6-13c4-11e6-89d0-7cd21f0976a9.jpg)

**Comment by tomekpiotrowski** [comment] 2016-05-08 08:25
This must be a problem caused by a conflict with other mods, as you say yourself things started going south when you've added more mods. You'd have to start with a fresh install again and figure out exactly which combination of mods is causing problems. Otherwise there's not much we can do.

**Comment by LordFlameStryke** [comment] 2016-05-08 08:56
Ok, thanks.  One of the problems with an easy to mod game is the overabundance of mods.  I'll try to figure out which mod(s) are causing the conflict.

**Comment by KSP-TaxiService** [comment] 2018-07-19 13:51
Closed as no further communication is received and the root cause is the usual mod conflict.

**Closed by KSP-TaxiService** 2018-07-19 13:51 UTC
Labels: Other Mod
