### ISSUE TITLE
Remote Tech contracts vanished

### ISSUE THREAD

**Issue by NikPower** [RemoteTechnologiesGroup/RemoteTech#741] opened 2017-11-25 20:59 UTC
Updated KSP from 1.3.0 to 1.3.1,
Updated Remote Tech from 1.8.8 to 1.8.9
Remote Tech contracts vanished :((

**Comment by KSP-TaxiService** [comment] 2017-11-26 06:00
Hi,
Please provide your [log](https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/develop/CONTRIBUTING.md#bug-reports) and a short description of what was happening during your KSP and RT upgrades. Did your accepted contracts disappear after the upgrades?

**Comment by NikPower** [comment] 2017-11-26 10:17
O.S: Windows 7 64 bits 
KSP: v 1.3.1 64 bit
Problem: 

Reproduction steps:
1. I was using KSP version 1.3.0 and RT version 1.8.8 - Remote Tech contracts were OK,
2. then updated KSP to 1.3.1 and SCAN said RT 1.8.9 is available
    I updated RT to 1.8.9 via SCAN
3. I've started the new career in KSP 1.3.1 + RT 1.8.9 - Remote Tech contracts were not available in mission control
4. I downloaded RT 1.8.8.10 manually and unzipped it into GameData - Remote Tech contracts become available
5. Conclusion - looks like old Contract Pack: Remote Tech 2.1.4 by Nightingale is not compatible with new Remote Tech 1.8.9

**Comment by steffenbanhardt** [comment] 2017-11-26 12:50
Uploading my KSP.log -- There are many errors like this one:

 ContractConfigurator.ParameterFactory: CONTRACT_TYPE 'RT_EverythingSat',PARAMETER 'KSCConnectivity' of type 'KSCConnectivity': Unknown parameter 'KSCConnectivity'.

 ContractConfigurator.HasAntennaFactory: CONTRACT_TYPE 'RT_EverythingSat', PARAMETER 'HasAntenna' of type 'HasAntenna': Error parsing antennaType

[KSP.log](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/1503903/KSP.log)

**Comment by KSP-TaxiService** [comment] 2017-11-26 13:03
@NikPower @steffenbanhardt Hey, thanks for details provided! I am bluffed by this bug because I do not make any change in RT 1.8.9 that would cause this contract issue.

You may be interested to know the [ContractConfigurator thread](https://forum.kerbalspaceprogram.com/index.php?/topic/91625-131-contract-configurator-v1233-2017-10-05/&page=165) has various bug reports on contract vanishing. 

I am going to try to pinpoint down to the root cause on my side.

**Comment by KSP-TaxiService** [comment] 2017-11-27 14:16
I found [one ](https://github.com/RemoteTechnologiesGroup/RemoteTech/commit/30fd599f1592620d3dcaf2ec64104d59e4195399)of the RT 1.8.9 changes that causes ContractConfigurator to go apeshit. I am guessing CC was compiled against RT 1.8.8 and didn't expected the new attributes added by myself. 

I will report this to the CC thread with what I found.

**Comment by KSP-TaxiService** [comment] 2018-02-15 16:12
It seems the CC mod isn't updated for while.

I am going to close this issue as there isn't anything to fix this bug on RT side. :-(

**Closed by KSP-TaxiService** 2018-02-15 16:12 UTC
Labels: Other Mod, Verified Bug
