### ISSUE TITLE
Light Actions not working with 1.1.2

### ISSUE THREAD

**Issue by james3838** [RemoteTechnologiesGroup/RemoteTech#605] opened 2016-05-02 06:28 UTC
I think this is a new issue, as I've always done this.  Create new unmanned ship.  Set the antennas and solar panel to activate with lights.  Launch rocket...

The light icon seems unclickable.  Didn't try numeric action groups.

**Comment by MacEriu** [comment] 2016-05-04 05:24
I also have this issue. Lights, gear, brakes and the abort button not working with unmanned probes. With nether installed light or action groups.

**Comment by gnivler** [comment] 2016-05-04 23:11
Also confirmed with stock + 528

Stayputnik + DP-10

L)ights and G)ear keyboard shortcuts don't work, with a connection.  Assigning to action keys 1 and 2 respectively works for both though.

The GUI buttons for each are perhaps behaving strangely too:

With or without lights, the button appears the same.  With gear, the button changes indicating there is gear (and without the button reflects there is no gear)

**Comment by KSP-TaxiService** [comment] 2018-07-19 14:35
I am tracking this issue under #646 since it concerns RT's input locks on staging, RCS, SAS and action. These locks have funny effects on KSP's interface components and no good solution is yet to be found.

**Closed by KSP-TaxiService** 2018-07-19 14:35 UTC
Labels: UI, Verified Bug
