### ISSUE TITLE
Problem with remote tech

### ISSUE THREAD

**Issue by Zed202020** [RemoteTechnologiesGroup/RemoteTech#518] opened 2015-12-12 00:37 UTC
I downloaded the 1.0.5 version for my Windows 10 Pc a week ago and everything work fine, I can make survey.....
few days after I m just add the last version of the mods......... and at this point I cant add the antenna to my probe on the VAB. when I put it on the probe I got an warning when I m in the vab that's there s no antenna to transmit data
so I remote all the mods one by one and I finaly realize the problem is the remotetech v 1.6.9!!!!!
the module manager files stop you using the antenna to transmit the DATA or make survey.
I hope it will be a solution soon (sorry for my English) ;-)

**Comment by Zed202020** [comment] 2015-12-12 15:42
I tried something who apparently work.... when yon put antenna in the body of the probe you can t transmit data but you add its green dot on the green dot of the probe yon can transmit data. i don t know why!!!

**Comment by FourWindBadger** [comment] 2015-12-19 11:23
How did you get this to work? I tried putting the antenna on top of the "probe" green dot? 
http://prntscr.com/9g0333

**Comment by Zed202020** [comment] 2015-12-20 02:19
yeah I put the antenna on top of a green dot and now I can make survey and
sending data.

2015-12-19 6:23 GMT-05:00 FourWindBadger <notifications@github.com>:

**Comment by FourWindBadger** [comment] 2015-12-20 10:37
Weird doesn't work for me :/

**Comment by spratt** [comment] 2015-12-23 18:12
Same issue, I think.  I'm getting the science from a resource survey, but not the overlay.

**Comment by FourWindBadger** [comment] 2015-12-23 20:54
Well i haven't checked that :) 

But i guess i would get it :)

hope they fix it soon

**Comment by tomekpiotrowski** [comment] 2016-04-23 20:30
Anyone encountering this with RT 1.6.11 and KSP 1.1?

**Comment by lamont-granquist** [comment] 2016-05-07 22:35
if i'm parsing it correctly this is a dup of #524 (i don't have survey scanners or science labs up in orbit yet in my career game, so i haven't verified fixed or not).

**Comment by gnivler** [comment] 2016-05-07 22:59
I am not able to reproduce this with 1.7.0 on KSP 1.1.2

**Comment by tomekpiotrowski** [comment] 2016-05-07 23:01
I guess we'll close it for now then. We can always re-open if needed.

**Closed by tomekpiotrowski** 2016-05-07 23:01 UTC
Labels: Old Issue: Reconfirm
