### ISSUE TITLE
No distance lag

### ISSUE THREAD

**Issue by gaultesian** [RemoteTechnologiesGroup/RemoteTech#519] opened 2015-12-15 14:44 UTC
Since 1.05, I have noticed I do not have any lag at transmitting or commanding remotely piloted probes or satellites (i.e. the further one goes from Kerbin, there is no lag penalty time in the upper left corner in the time acceleration tab).  Everything now is instantaneous with regards to contacting KSC from probes as far away as Eeloo.

**Comment by tomekpiotrowski** [comment] 2016-04-23 20:39
Are you still encountering this with RT 1.6.11 and KSP 1.1?

**Comment by gaultesian** [comment] 2016-04-23 21:04
I am still on 1.05, and I still have the issue there.  Once I go to 1.1 (later this weekend), I will definitely give it a test - thanks a million for inquiring on this, as RT is one of the best mods for KSP.

**Comment by keyspace** [comment] 2016-06-30 13:07
Cannot reproduce on `KSP 1.1.3` with `RT build-develop-554`.

**Comment by keyspace** [comment] 2016-10-01 12:36
Cannot reproduce with current stable (`RT 1.7.1`). OK to close IMO.

**Comment by neitsa** [comment] 2016-10-01 20:30
thank you @keyspace for checking this issue! Couldn't repro on my side either. Closing it.

**Closed by neitsa** 2016-10-01 20:30 UTC
Labels: Old Issue: Reconfirm
