### ISSUE TITLE
Science often fails to transmit from L-Tech's Skylab

### ISSUE THREAD

**Issue by scatterlogical** [RemoteTechnologiesGroup/RemoteTech#675] opened 2016-08-30 11:03 UTC
Science transmission is intermittently broken from L-Tech's Skylab. It goes thru the motions, counting to 100%, then sometimes it gives me science, other times it won't. I've been working around the problem by quicksaving before transmitting, then if it fails, just reload. Doesn't always work again the next time tho, could take a few reloads. All other science transmits fine. Seems there has been a similar problem in the past with sending science while using RemoteTech, I thought this could be a related issue.

**Comment by neitsa** [comment] 2016-11-10 09:27
Quite sure this is a duplicate of issue #667. Commit 17b2b85 addresses this problem.

**Closed** 2016-11-10 09:27 UTC
Labels: Duplicate, Other Mod, Transmission
