### ISSUE TITLE
Execute actions are forgotten when changing vessels

### ISSUE THREAD

**Issue by BlackSoldierB** [RemoteTechnologiesGroup/RemoteTech#424] opened 2015-05-17 14:00 UTC
I am building an RT network, therefore i chose to launch three comsat's with one manned vessel. 
I decouple all three of them, when I am in rage of the KSC. For each sat I have created maneuver node's, executed the "point to node" command and executed the "EXEC" command.

When i switched back to the first sat, the "EXEC" command was no longer in the list.

**Comment by Peppie23** [comment] 2015-05-17 14:04
@BlackSoldierB yep thats an issue on our current release. So i'll mark this as an duplicate of  #403 because we've already fixed that issue.

Btw. v1.6.5 will be released tomorrow, if you don't want to wait, you can use our current dev-build 378

Thanks for your report.

**Closed by Peppie23** 2015-05-17 14:04 UTC

**Comment by BlackSoldierB** [comment] 2015-05-17 14:18
Thanks for the fast reply. Keep up the good work :D
