### ISSUE TITLE
KSP lockup when physics is loading and active antennas in different SOI's

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#12] opened 2014-05-26 04:03 UTC
Original issue at Cilph/RemoteTech2#164.

BigD145 wrote:

> This has occurred in a couple situations, but the root cause seems to be when coming out of high warp and physics kicks in or when loading a vehicle from the KSP tracking station or switching active vessels and physics kicks in. So far it has only happened when there are active long range (350Gm, 400Gm, or 60Gm) antennas connecting two vessels that are in two different SOI's (Kerbin/Jool and Jool/Sun).

**Comment by KSP-TaxiService** [comment] 2016-11-10 13:01
I can't reproduce this lockup bug on the stock KSP 1.2.1604 with the latest RT develop. With two pairs of long-range satellites in Kerbin, Sun and Jool SOIs, wrapping or loading a vehicle does not result in any freeze.

**Comment by neitsa** [comment] 2016-11-10 14:05
Thanks for the heads-up @KSP-TaxiService ; if you feel inclined to do so, maybe we could close the issue as it is no more reproducible (and add a "Can't Reproduce" tag)?

**Comment by KSP-TaxiService** [comment] 2016-11-10 14:25
Yes, we can close the issue and add this tag. KSP was improved massively in terms of physics now.

**Closed** 2016-11-10 14:53 UTC
Labels: Can't Reproduce, From Cilph/RemoteTech2
