### ISSUE TITLE
Inability to switch "mode" to "off"

### ISSUE THREAD

**Issue by rsparkyc** [RemoteTechnologiesGroup/RemoteTech#530] opened 2016-03-10 21:12 UTC
I know I can kill an orientation lock by clicking on the `x` in the flight computer screen, but I'd like the ability to schedule that action.  For instance, I want to execute the next node: I prep my ship by setting `node` orientation about 30s before my planned burn, and then I execute the next node.  When I'm done, however, my orientation lock is still set to `node`.  I can set it to `kill`, however if I don't disable RCS, my craft will still burn RCS while it tries to stabilize.  Honestly, I don't care if my craft continues to spin after my node execution, so is there a way to send a `cancel orientation lock` command?

**Comment by gnivler** [comment] 2016-04-24 07:41
I was able to get this effect by changing line 89 in ManeuverCommand.cs

computer.Enqueue(AttitudeCommand.KillRot(), true, true, true);
to
computer.Enqueue(AttitudeCommand.Off(), true, true, true);

but I don't feel I have any business doing this for other than personal reasons... I do prefer it this was though.

**Comment by d4rksh4de** [comment] 2016-04-24 07:52
Sounds reasonable, because you can always append the `KILL` command if you want it to stop spinning.

**Comment by gnivler** [comment] 2016-04-24 23:26
Good "news" - having FC move to Off after execution doesn't prevent 'maintain stability' objectives despite the rotation

**Comment by gnivler** [comment] 2016-04-26 14:37
Regarding adding a `KILL` to the end, you have to manually enter the signal delay so that it gets appended.  Just clicking `KILL` seems to prepend it which is immediately executed.

Reproduce by
Set a maneuver node
`EXEC`
`KILL`

You're left with just the maneuver queued.  If you set a signal delay manually (presumably after the maneuver execution, which would be math of burn time + execution time) and `KILL` it gets appended and runs normally.

**Comment by neitsa** [comment] 2016-10-18 15:56
This was fixed by @gnivler on #631 where you can change this behavior with a settings in the the config. file.

I'm still leaving this open to add an option in the FC UI so it's would be easier to access.

- [x] Attitude "Off" config. through setting 
- [ ] Attitude "Off" with FC UI

**Closed** 2016-10-29 16:36 UTC
Labels: FlightComputer, Staged
