### ISSUE TITLE
"Transfer crew" button in context popup menu should be always available

### ISSUE THREAD

**Issue by mscg82** [RemoteTechnologiesGroup/RemoteTech#626] opened 2016-05-09 10:33 UTC
Try to build this craft in the SPH:

1. Place Mk1 Lander Can as root
2. Attach any probe to the left attach node
3. Attach Mk1 Crew Cabin to the other node

Now launch the craft and transfer Jeb from the lander can to the crew cabin. The connection status will switch to "No connection" and the "Transfer crew" button in the context menu of the the crew cabin will not work. You can still transfer Jeb back to the lander can by clicking on the free hatch of the crew cabin, but if you have anything attached to the rear attach node of the crew cabin (as in a real craft) this option is no more available and you're stuck with Jeb in the crew cabin, unable to move.
Moreover, if you remove the probe from the craft, the "Transfer crew" button works fine.

**Comment by neitsa** [comment] 2016-10-03 16:07
Sounds a little bit like #628 (although I'm not really sure). I think the problem is somewhere on the ModuleSPU code, I'll need to dig onto that. I'll keep you updated.

**Comment by neitsa** [comment] 2016-10-08 23:26
@mscg82 Couldn't repro anymore on the current dev branch.

Valentina transferred to the cabin without any problem (notice the delay indicator turned to delay rather than "Local control", this is intended as only Command Stations have local control even if there's nobody in a command module):

![screenshot4](https://cloud.githubusercontent.com/assets/4538670/19216503/9f80a47a-8dbe-11e6-9935-ae42b0e9edc4.png)

I can still transfer Valentina into the the lander can without problems (the ship is back to "local control" as she is in a command module):

![screenshot5](https://cloud.githubusercontent.com/assets/4538670/19216511/14537cdc-8dbf-11e6-98ae-06c61c1e5bb8.png)

I'm closing this issue. However, feel free to reopen this issue when the upcoming version is released (for KSP 1.2) if you think it still doesn't work as intended. Thank you!

**Closed by neitsa** 2016-10-08 23:26 UTC
Labels: Bug

**Comment by mscg82** [comment] 2016-10-09 08:22
Thanks @neitsa. I think that your craft has a radio connection with the command control through the integrated antenna in the probe core. Can you try to disable the antenna on the probe so that you switch to a "no connection" status when you move Jeb out of the command pod (as it happens in an early career, when the integrated antenna has not been unlocked in the tech tree)?

**Comment by neitsa** [comment] 2016-10-09 12:22
I'm really sorry @mscg82, I was too quick to close the issue. This is nonetheless fixed on dev branch in commit e0d3581.

This time in space around Kerbin without any sats nearby and no antenna on the craft. Transfering the kerbel from the command module (lander can) to the cabin. Notice "Local Control" is red which means there's no connection, **only** local control:

![screenshot6](https://cloud.githubusercontent.com/assets/4538670/19220285/4c1766fe-8e2a-11e6-8b07-b9436ef414d7.png)

Kerbal in the cabin, no connection at all:

![screenshot7](https://cloud.githubusercontent.com/assets/4538670/19220299/b61363b4-8e2a-11e6-9a79-c83d4ef2ba71.png)

Transfering back from cabin to lander can:

![screenshot8](https://cloud.githubusercontent.com/assets/4538670/19220302/cdcf1552-8e2a-11e6-9207-eeffa8afd52a.png)

Back to the lander can, we have now local control over the the vessel:

![screenshot9](https://cloud.githubusercontent.com/assets/4538670/19220311/fd5c8642-8e2a-11e6-9432-237e6807e1ac.png)

Note: all transfers are done with the "Transfer crew" part action so I think that solve the issue. This also bypass any sort of delay (if the craft is far from any connection source but still connected) that could incur and is an immediate action.

Thank you for your report and comments! I'm still leaving this issue closed but will add it to the changelog for the next version. In any case you think this issue is not properly fixed in the upcoming release, feel free to comment or open it once again.

**Comment by mscg82** [comment] 2016-10-09 15:01
Thanks for your work, @neitsa! I think that the issue is definitively closed now.
