### ISSUE TITLE
Partial loss of control after undock

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#4] opened 2014-05-26 03:37 UTC
Original issue at Cilph/RemoteTech2#175.

tal2410 wrote:
> When I undock two vessels, only one of them remains controllable. Both have a connection (green icon: and omni line in map view), electric charge, command pod, antennas...
> 
> Sometimes, the vessel without a connection can still change attitude if SAS was left disabled, but everything else is unavailable (SAS, RCS, thrust, action group).

**Comment by somtaaw** [comment] 2015-05-16 14:46
Unable to reproduce this issue, possibly fixed.

**Comment by Peppie23** [comment] 2015-05-16 20:35
Yep it should be fixed. The second part is also related to #95, so we'll close this issue.

**Closed by Peppie23** 2015-05-16 20:35 UTC
Labels: From Cilph/RemoteTech2, Old Issue: Reconfirm
