### ISSUE TITLE
Commands from SAS are not delayed 

### ISSUE THREAD

**Issue by dtondo** [RemoteTechnologiesGroup/RemoteTech#663] opened 2016-07-03 04:55 UTC
Hi,

If I'm in a big distance (sample +  5 seconds) Activate sas is delayed well.  nevertheless when I click on sas retrograde, for instance, it start to move the vessel instantaneously with out the right delay.

**Comment by neitsa** [comment] 2016-10-06 01:21
@dtondo : could not reproduce with the latest build (stock + RT). Activating SAS with the 'T' button delay correctly. Clicking on flight computer buttons does the same (ship is orbiting Duna and transmitter is in LKO, 109 seconds delay):

![screenshot3](https://cloud.githubusercontent.com/assets/4538670/19137333/48699144-8b73-11e6-9378-ddd318b6afb7.png)

The precise version of RT you are using and a log file would be useful.

Tell me if you can still experience this bug, otherwise I'll close the issue.

**Comment by YamoriYuki** [comment] 2016-10-15 22:27
I've checked this one on plain KSP1.2+RT1.8.0 and native SAS commands (controls next to the navball) are delayed and the time seems about right.
What is a bit confusing is that these commands do not appear in Flight Computer queue.
Maybe using it this way was not intended? I sure never did, so I have no idea if thay did show before.

**Closed** 2017-03-02 14:28 UTC
Labels: Verified Bug
