### ISSUE TITLE
Partial control with hybrid probe/antenna

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#224] opened 2014-10-21 22:50 UTC
dtoxic on the forums reported that they get only partial control when modifying a hybrid probe/antenna from the LionHead mod to not require a connection to KSC (i.e., removing `ModuleSPU`). Specifically, they can only use continuous keypress commands (throttle, slewing, etc), but not commands that require a toggle of some sort (SAS, RCS, staging). They claim the bug only appeared when updating from 1.4.1 to 1.5.

This is probably related to #213, and I think it means that part modules may have unexpected conflicts when installed on the same part (clearly everything works fine when these modules are all on the same vessel, as would happen if you combined an unsupported probe core with a separate RT antenna).

dtoxic's exact config is attached below.

```
@PART[LH_Hermes]
{
MODULE
{
name = ModuleRTAntenna
Mode0DishRange = 0
Mode1DishRange = 800000000000
EnergyCost = 0.90
DishAngle = 5.50

TRANSMITTER
{
PacketInterval = 0.3
PacketSize = 2
PacketResourceCost = 15.0
}
}

MODULE
{
name = ModuleSPUPassive
}

MODULE
{
name = ModuleRTAntennaPassive
OmniRange = 3000000

TRANSMITTER
{
PacketInterval = 0.3
PacketSize = 2
PacketResourceCost = 15.0
}
}
}
```

**Comment by sick13** [comment] 2015-01-20 17:11
any progress on this? :)

**Comment by ArSn** [comment] 2015-01-24 13:32
I am having a look into this right now.

**Comment by sick13** [comment] 2015-01-24 15:46
cool thx :)

**Comment by ArSn** [comment] 2015-01-25 16:30
@sick13 I took a deeper look into this issue yesterday and it lead me to the conclusion that we need some further discussion before I just implement something that I think should be appropriate.

@RemoteTechnologiesGroup: I would also very much like to hear you other guys' opinions about the following.

The description that @Starstrider42 originally posted in this issue suggests, that one could not configure the `ModuleSPU` module for a part and just only configure `ModuleSPUPassive` instead, which would then lead to the part not requiring a connection to KSC in order to be operateable.
It also seems, that this was in fact possible so far with the code that RT is currently imploying.

However, I would assume that this is actually a bug rather than a feature, as I imagine that RT is having some ground rules:
- Manned vehicles can be controlled from local in real time.
- ALL(!) unmanned vehicles require a connection to KSC (or a CommandStation) in order to be operateable.
- As long as there is no probe core part (`ModuleSPU`) present on the vehicle, the FlightComputer can not be used, even if a connection is established.

Now one can argue about the realism of whether the vehicle should actually operateable if there is a connection but no flight computer (i.e. there is an antenna but no probe core, an `ModuleSPUPassive` but no `ModuleSPU`). In my opinion I would say: No. The flight computer is what handles the SAS, RCS, thrust and son on from remote.
If anything (again, in my opinion) the antenna-only-vehicle should be able to operate as a signal relay.

So what I am saying here is two points: 
1. The fact that you are currently able to operate the vehicle that only uses `ModuleSPUPassive` even though you do not have an connection established is a bug. This should be fixed.
2. I still can reproduce the problem that you can not use any input-locked switches (SAS, RCS and so on) when you undocked your satellite. This is however a different issue that has to de with the handling of the input locks and we should be able to fix also.

I would like to clear things up before I implement any solution for this which will then lead to discussion afterwards because it may not be the thing that you guys expected. ;)

Thanks in advance for your response and thoughts!

**Comment by sick13** [comment] 2015-01-26 02:02
yeah sure my take on that (i don't know if it's a bug or not) but by removing ModuleSPU from "Part.cfg" would make RT be a bit easier to play for Newbies like me

 but if it causes a problem then by all means implement that what witch has the least problems :)

**Comment by ArSn** [comment] 2015-01-26 22:36
Well, the point of RT is to add an extra layer of difficulty and realism to the game, and therefore I would say being more newbie-friendly would be the exact opposite of it. Plus it would as well be kind of unrealistic then too again.

just my 2 cents

**Comment by sick13** [comment] 2015-01-26 23:13
agreed @ArSn but my take on it is that you have to manually modify every "CFG" file to achieve the newbie behavior thus it is not integrated into RT so to speak just like signal Delay play with it or just edit the Settings file... in my opinion its good to hove multiple option's for various tastes :)

**Comment by KSP-TaxiService** [comment] 2018-07-19 15:33
Ehhh, I am not sure if I understand this issue correctly. The LionHead mod seems to be sort of real-world replicates with different modules, like solar panel or comm, integrated. 

As I see that today third-party modifications to RT configs/parts are far rare and non-invasive, I think it is in our best interest that this should be closed and new issues arisen on such third-party modifications should be considered on case by case basic.

**Closed by KSP-TaxiService** 2018-07-19 15:33 UTC
Labels: Verified Bug
